export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE='ADD_TODO_FAILURE';
export const ADD_TODO_STARTED='ADD_TODO_STARTED';

export const SEARCH_DETAIL_SUCCESS='SEARCH_DETAIL_SUCCESS';
export const SEARCH_DETAIL_FAILURE='SEARCH_DETAIL_FAILURE';
export const SEARCH_DETAIL_STARTED='SEARCH_DETAIL_STARTED';

export const DELETE_TODO='DELETE_TODO';
export const UPDATE_SEARCHED_VALUE='UPDATE_SEARCHED_VALUE';
export const UPDATE_SELECTED_SERIES='UPDATE_SELECTED_SERIES'